// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKey(arg1, arg2) {
  return window['go']['main']['App']['GetKey'](arg1, arg2);
}

export function GetKeyAndMods(arg1, arg2) {
  return window['go']['main']['App']['GetKeyAndMods'](arg1, arg2);
}

export function GetModifiers(arg1, arg2) {
  return window['go']['main']['App']['GetModifiers'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
