// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHID():Promise<any>;

export function FactoryReset():Promise<void>;

export function GetNormalKeyOfLayout1(arg1:number,arg2:number):Promise<string>;

export function GetNormalKeyOfLayout2(arg1:number,arg2:number):Promise<string>;

export function GetNormalModifiersOfLayout1(arg1:number,arg2:number):Promise<number>;

export function GetNormalModifiersOfLayout2(arg1:number,arg2:number):Promise<number>;

export function GetUpperKeyOfLayout1(arg1:number,arg2:number):Promise<string>;

export function GetUpperKeyOfLayout2(arg1:number,arg2:number):Promise<string>;

export function GetUpperModifiersOfLayout1(arg1:number,arg2:number):Promise<number>;

export function GetUpperModifiersOfLayout2(arg1:number,arg2:number):Promise<number>;

export function LoadKeymapFromKeyboard():Promise<void>;

export function Restart():Promise<void>;
