// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKey(arg1:number,arg2:number):Promise<string>;

export function GetKeyAndMods(arg1:number,arg2:number):Promise<string|number>;

export function GetModifiers(arg1:number,arg2:number):Promise<number>;

export function Greet(arg1:string):Promise<string>;
