// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHID() {
  return window['go']['main']['App']['CheckHID']();
}

export function FactoryReset() {
  return window['go']['main']['App']['FactoryReset']();
}

export function GetNormalKeyOfLayout1(arg1, arg2) {
  return window['go']['main']['App']['GetNormalKeyOfLayout1'](arg1, arg2);
}

export function GetNormalKeyOfLayout2(arg1, arg2) {
  return window['go']['main']['App']['GetNormalKeyOfLayout2'](arg1, arg2);
}

export function GetNormalModifiersOfLayout1(arg1, arg2) {
  return window['go']['main']['App']['GetNormalModifiersOfLayout1'](arg1, arg2);
}

export function GetNormalModifiersOfLayout2(arg1, arg2) {
  return window['go']['main']['App']['GetNormalModifiersOfLayout2'](arg1, arg2);
}

export function GetUpperKeyOfLayout1(arg1, arg2) {
  return window['go']['main']['App']['GetUpperKeyOfLayout1'](arg1, arg2);
}

export function GetUpperKeyOfLayout2(arg1, arg2) {
  return window['go']['main']['App']['GetUpperKeyOfLayout2'](arg1, arg2);
}

export function GetUpperModifiersOfLayout1(arg1, arg2) {
  return window['go']['main']['App']['GetUpperModifiersOfLayout1'](arg1, arg2);
}

export function GetUpperModifiersOfLayout2(arg1, arg2) {
  return window['go']['main']['App']['GetUpperModifiersOfLayout2'](arg1, arg2);
}

export function LoadKeymapFromKeyboard() {
  return window['go']['main']['App']['LoadKeymapFromKeyboard']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}
